# base configs from: https://raw.githubusercontent.com/prometheus/jmx_exporter/main/example_configs/kafka-2_0_0.yml
lowercaseOutputName: true
lowercaseOutputLabelNames: true
whitelistObjectNames: ["*:*"]
