##
# Copyright 2023 Aiven Oy
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##
version: '3.8'
services:
  zookeeper:
    image: "confluentinc/cp-zookeeper:7.3.3"
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: "aivenoy/kafka:3.3-2022-10-06-tiered-storage-1-ts-2"
    container_name: "kafka-ts"
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,BROKER://0.0.0.0:29092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092,BROKER://kafka:29092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,BROKER:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "BROKER"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
      # Tweak retention checking
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 10000
      # Enable Tiered Storage
      KAFKA_REMOTE_LOG_STORAGE_SYSTEM_ENABLE: true
      KAFKA_REMOTE_LOG_MANAGER_TASK_INTERVAL_MS: 5000
      # Remote metadata manager
      KAFKA_REMOTE_LOG_METADATA_MANAGER_CLASS_NAME: "org.apache.kafka.server.log.remote.metadata.storage.TopicBasedRemoteLogMetadataManager"
      KAFKA_RLMM_CONFIG_REMOTE_LOG_METADATA_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_REMOTE_LOG_METADATA_MANAGER_LISTENER_NAME: BROKER
      # Remote storage manager
      KAFKA_REMOTE_LOG_STORAGE_MANAGER_CLASS_PATH: "/tiered-storage-for-apache-kafka/*"
      KAFKA_REMOTE_LOG_STORAGE_MANAGER_CLASS_NAME: "io.aiven.kafka.tieredstorage.RemoteStorageManager"
      KAFKA_RSM_CONFIG_CHUNK_SIZE: 1048576
      KAFKA_RSM_CONFIG_CHUNK_CACHE_CLASS: "io.aiven.kafka.tieredstorage.cache.UnboundInMemoryChunkCache"
      # Storage backend
      KAFKA_RSM_CONFIG_KEY_PREFIX: "tiered-storage-demo/"
      KAFKA_RSM_CONFIG_STORAGE_BACKEND_CLASS: "io.aiven.kafka.tieredstorage.storage.s3.S3Storage"
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      KAFKA_RSM_CONFIG_STORAGE_AWS_CREDENTIALS_PROVIDER_CLASS: "com.amazonaws.auth.EnvironmentVariableCredentialsProvider"
      KAFKA_RSM_CONFIG_STORAGE_S3_BUCKET_NAME: ${KAFKA_RSM_CONFIG_STORAGE_S3_BUCKET_NAME}
      KAFKA_RSM_CONFIG_STORAGE_S3_REGION: ${KAFKA_RSM_CONFIG_STORAGE_S3_REGION}
