name: add comment to jira issue
on:
  issue_comment:
    types:
      [created, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    name: add new comment
    steps:
    - name: checkout repo content
      uses: actions/checkout@v2 # checkout the repository content to github runner.
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 #install the python needed

    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: ticket_num
      run: |
        output=$(python .github/workflows/ticket_number.py "${{ github.event.issue.title }}")
        echo "::set-output name=ticket::$output"
      id: ticket_extraction


    - name: Comment on issue
      if: ${{ github.event.comment.body != 'in progress' && github.event.comment.body != 'selected for development' && github.event.comment.body != 'waiting for upstream'}}
      uses: atlassian/gajira-comment@master
      with:
        issue: ${{ steps.ticket_extraction.outputs.ticket }}
        comment: ${{ github.event.comment.body }}