name: Git Checks

on: [pull_request]

jobs:
  block-fixup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Block Fixup Commit Merge
      uses: alexkappa/block-fixup-merge-action@v2

    - name: Gen docs
      run: make docs

    - name: Check for uncommitted documentation changes
      run: |
        if [[ -n $(git status -s) ]]; then
          echo "There are uncommitted changes after the task:"
          git status -s
          echo "Update the documentation on the proper *Config.java and commit generated docs"
          exit 1
        else
          echo "No changes detected."
        fi
      shell: bash
